name: student_printing_system
description: A Flutter application for student printing management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.3.0
  firebase_messaging: ^14.2.0
  provider: ^6.1.1
  file_picker: ^10.3.3
  permission_handler: ^11.0.1
  intl: ^0.18.1
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true