// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<api reducted, use your own>',
    appId: '1:38499636597:web:29ff2b8d2a3ee8b0e02f3c',
    messagingSenderId: '38499636597',
    projectId: 'print-management-app',
    authDomain: 'print-management-app.firebaseapp.com',
    storageBucket: 'print-management-app.firebasestorage.app',
    measurementId: 'G-X0JPNQQ0LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFc7oVrlnlca-rGR6cyx0cvk-LQUifmz8',
    appId: '1:38499636597:android:fcd689c0f1425022e02f3c',
    messagingSenderId: '38499636597',
    projectId: 'print-management-app',
    storageBucket: 'print-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpgX6oMQnlPywHyDWFFDBL8V5Jjw-Wlk',
    appId: '1:38499636597:ios:67b4c1e00cfb8a61e02f3c',
    messagingSenderId: '38499636597',
    projectId: 'print-management-app',
    storageBucket: 'print-management-app.firebasestorage.app',
    iosBundleId: 'com.example.MMCOEPrintHelper.printManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpgX6oMQnlPywHyDWFFDBL8V5Jjw-Wlk',
    appId: '1:38499636597:ios:67b4c1e00cfb8a61e02f3c',
    messagingSenderId: '38499636597',
    projectId: 'print-management-app',
    storageBucket: 'print-management-app.firebasestorage.app',
    iosBundleId: 'com.example.MMCOEPrintHelper.printManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4XrdLKBPplcPX5IfFrcSTAZ1CuGryMb0',
    appId: '1:38499636597:web:a5266966f6d826e1e02f3c',
    messagingSenderId: '38499636597',
    projectId: 'print-management-app',
    authDomain: 'print-management-app.firebaseapp.com',
    storageBucket: 'print-management-app.firebasestorage.app',
    measurementId: 'G-CV04SC9ZBR',
  );

}
